<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>ToDo App</title>
	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
</head>
<body>
<h1>Add ToDo</h1>

<form action="/addToDo" method="post">
	<input type="text" name="task" placeholder="Add Task"><br>
	<input type="radio" name="priority" value="1"> High<br>
	<input type="radio" name="priority" value="2"> Medium<br>
	<input type="radio" name="priority" value="3"> Low<br>

	<input type="submit" value="Submit">

</form>

</body>
</html>
