<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>ToDo App</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<link rel="stylesheet" href="styles/styles.css">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" defer></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" defer></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" defer></script>
</head>
<body>
<div class="container-fluid">
	<div class="row h-100">
		<div class="col-3 bg-light">
			<div id="list-container">
				<?php echo \ToDos\ViewHelpers\DisplayToDosTasksViewHelper::displayToDoLists($id['id'], $toDosLists);?>
				<div class="row d-flex align-items-center pl-3">
					<form action="/addToDoList" method="post">
						<input id="addList-input" class="bg-transparent border-0" type="text" name="list_name">
						<input type="submit" value="Submit" id="addList_submit" class="d-none">
					</form>
				</div>
				<div class="row fixed-bottom pl-4">
					<div>
						<button class="bg-transparent border-0" id="addList-button"><i class="fas fa-plus-circle pr-2"></i>Add List</button>
					</div>
				</div>
			</div>
		</div>
		<div class="col-9">
			<?php echo \ToDos\ViewHelpers\DisplayToDosTasksViewHelper::displayToDosList($id,$toDosTasks);?>
		</div>
	</div>
</div>
<?php echo \ToDos\ViewHelpers\DisplayToDosTasksViewHelper::displayEditTaskModal($toDosLists, $toDosTasks);?>

<script src="https://unpkg.com/ionicons@4.5.5/dist/ionicons.js"></script>
<script>

    document.getElementById("addTask-button").addEventListener("click", function(){
        document.getElementById("addTask-input").focus();
    });

    document.getElementById("addTask-input").addEventListener("focusout", function(){
        document.getElementById("addTask_submit").click();
    });

    document.getElementById("addList-button").addEventListener("click", function(){
        document.getElementById("addList-input").focus();
    });

    document.getElementById("addList-input").addEventListener("focusout", function(){
        document.getElementById("addList_submit").click();
    });

    var inputs = document.querySelectorAll(".editTask-input");
    var info_btns = document.querySelectorAll(".editInfo");

    for (var j = 0; j < inputs.length; j++) {
        let current = info_btns[j].getAttribute('id');
        inputs[j].addEventListener("focusin", function () {
	        document.getElementById(current).classList.remove("d-none");
        });
    }

    var completeInputs = document.querySelectorAll(".completeTask-input");
    var complete_btns = document.querySelectorAll(".completeTask_submit");
    for (var c = 0; c < completeInputs.length; c++) {
        let current = complete_btns[c].getAttribute('id');

        completeInputs[c].addEventListener("focusout", function () {
            document.getElementById(current).click();
        });
    }

    var lists = document.getElementById("list-container");
    var btns = lists.getElementsByClassName("list-name");
    for (var i = 0; i < btns.length; i++) {
        btns[i].setAttribute('id', i);
        btns[i].addEventListener("click", function() {
            var current = document.getElementsByClassName("active");
            if (current.length > 0) {
                current[0].className = current[0].className.replace(" active", "");
            }
            this.className += " active";
            var id = this.getAttribute('id');
        });
    }

    var activeInputs = document.querySelectorAll(".activeList-input");

    var active_btns = document.querySelectorAll(".activeList");

    for (var b = 0; b < activeInputs.length; b++) {
        let current = active_btns[b].getAttribute('id');

        activeInputs[b].addEventListener("focusin", function () {
            console.log(current);
            document.getElementById(current).click();
        });
    }
</script>
</body>
</html>